# Generated by Django 3.2.12 on 2022-03-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=80, verbose_name='Page')),
                ('link', models.CharField(max_length=80, verbose_name='Page Link')),
                ('priority', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Page Order')),
                ('has_sub', models.BooleanField(default=False, verbose_name='Sub Button')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_page_name', models.CharField(max_length=80, verbose_name='Sub Page')),
                ('link', models.CharField(max_length=80, verbose_name='Sub Page Link')),
                ('priority', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Sub Page Order')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menu', verbose_name='Parent Page')),
            ],
        ),
    ]
