# Generated by Django 3.2.12 on 2022-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220317_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Sub Title')),
                ('img_src', models.URLField(default='static/img/carousel/')),
                ('btn_text', models.CharField(default='no-button', max_length=80)),
            ],
        ),
    ]
