# Generated by Django 3.2.12 on 2022-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img_src',
            field=models.CharField(default='static/img/carousel/', max_length=80),
        ),
    ]
