# Generated by Django 3.2.12 on 2022-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_carousel_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sub Page Order'),
        ),
    ]
