# Generated by Django 3.2.12 on 2022-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220317_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('icon_class', models.CharField(max_length=80)),
                ('btn_text', models.CharField(default='no-button', max_length=80)),
                ('btn_link', models.CharField(default='', max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Icon Order')),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='btn_link',
            field=models.CharField(default='', max_length=80),
        ),
    ]
