# Generated by Django 3.2.12 on 2022-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220317_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='MainIcon',
        ),
    ]
