# Generated by Django 3.2.12 on 2022-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_icons_mainicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='btn_link',
            field=models.CharField(default='', max_length=80, verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='btn_text',
            field=models.CharField(default='no-button', max_length=80, verbose_name='Button'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img_src',
            field=models.CharField(default='home/img/carousel/', max_length=80, verbose_name='Image Static Link'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='btn_link',
            field=models.CharField(default='', max_length=80, verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='btn_text',
            field=models.CharField(default='no-button', max_length=80, verbose_name='Button'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='icon_class',
            field=models.CharField(max_length=80, verbose_name='FontAwesome Class'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='text',
            field=models.TextField(verbose_name='Sub Title Text'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
    ]
