# Generated by Django 3.2.12 on 2022-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220317_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('muted_title', models.CharField(max_length=80, verbose_name='Muted Title')),
                ('text', models.TextField(verbose_name='Sub Title Text')),
                ('style', models.CharField(choices=[('R', 'Right'), ('L', 'left')], max_length=1)),
                ('img_src', models.CharField(default='home/img/featurette/', max_length=80, verbose_name='Image Static Link')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Icon Order')),
            ],
        ),
    ]
