# Generated by Django 3.2.12 on 2022-03-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_featurette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'شريحة عرض', 'verbose_name_plural': 'شرائح العرض'},
        ),
        migrations.AlterModelOptions(
            name='featurette',
            options={'verbose_name': 'موضوع متميز', 'verbose_name_plural': 'موضوعات متميزة'},
        ),
        migrations.AlterModelOptions(
            name='mainicon',
            options={'verbose_name': 'أيقونة', 'verbose_name_plural': 'أيقونات'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'قائمة', 'verbose_name_plural': 'قوائم'},
        ),
    ]
