# Generated by Django 3.2.12 on 2022-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('home', '0011_auto_20220323_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='has_sub',
            field=models.BooleanField(default=False, verbose_name='زر قائمة فرعية؟'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=80, verbose_name='رابط الصفحة'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page_name',
            field=models.CharField(max_length=80, verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='link',
            field=models.CharField(max_length=80, verbose_name='رابط الصفحة الفرعية'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menu', verbose_name='تابع لـ'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب الفرعي'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='sub_page_name',
            field=models.CharField(max_length=80, verbose_name='الصفحة الفرعية'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='الاسم')),
                ('msg_type', models.CharField(choices=[('suggest', 'مقترح'), ('complain', 'شكوى')], max_length=8, verbose_name='نوع الرسالة')),
                ('msg_text', models.TextField(verbose_name='الرسالة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'نموذج تواصل',
                'verbose_name_plural': 'نماذج تواصل',
            },
        ),
    ]
