# Generated by Django 3.2.12 on 2022-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220323_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='btn_link',
            field=models.CharField(default='', max_length=80, verbose_name='رابط زر الضغط'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='btn_text',
            field=models.CharField(default='no-button', max_length=80, verbose_name='زر الضغط'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='caption',
            field=models.CharField(max_length=200, verbose_name='عنوان الشريحة'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img_src',
            field=models.CharField(default='home/img/carousel/', max_length=80, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.TextField(verbose_name='النص الفرعي'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='img_src',
            field=models.CharField(default='home/img/featurette/', max_length=80, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='muted_title',
            field=models.CharField(max_length=80, verbose_name='كلمة مميزة'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='style',
            field=models.CharField(choices=[('R', 'يمين'), ('L', 'يسار')], max_length=1, verbose_name='تنسيق العرض'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='text',
            field=models.TextField(verbose_name='النص الفرعي'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='title',
            field=models.CharField(max_length=80, verbose_name='عنوان الموضوع'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='btn_link',
            field=models.CharField(default='', max_length=80, verbose_name='رابط زر الضغط'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='btn_text',
            field=models.CharField(default='no-button', max_length=80, verbose_name='زر الضغط'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='text',
            field=models.TextField(verbose_name='النص الفرعي'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='title',
            field=models.CharField(max_length=80, verbose_name='عنوان الأيقونة'),
        ),
    ]
