# Generated by Django 3.2.12 on 2022-03-24 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220323_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'نموذج تواصل', 'verbose_name_plural': 'نماذج التواصل'},
        ),
        migrations.AddField(
            model_name='contact',
            name='msg_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='msg_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
