# Generated by Django 3.2.12 on 2022-03-24 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220324_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='توقيت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddField(
            model_name='featurette',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='توقيت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurette',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddField(
            model_name='mainicon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='توقيت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainicon',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='توقيت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='توقيت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
    ]
