# Generated by Django 3.2.12 on 2022-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_menu_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان الصفحة')),
                ('content', models.TextField(verbose_name='محتوى الصفحة')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'صفحات',
            },
        ),
    ]
