# Generated by Django 3.2.12 on 2022-03-27 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='رابط الصفحة'),
            preserve_default=False,
        ),
    ]
