# Generated by Django 3.2.12 on 2022-03-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='slug',
        ),
    ]
