# Generated by Django 3.2.12 on 2022-03-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_url_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='url',
        ),
    ]
