# Generated by Django 3.2.12 on 2022-03-28 22:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_slug_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainicon',
            name='btn_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='محتوى الصفحة'),
        ),
    ]
