# Generated by Django 3.2.12 on 2022-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220329_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.SlugField(unique=True, verbose_name='رابط الصفحة'),
        ),
    ]
