# Generated by Django 3.2.12 on 2022-03-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainicon',
            name='btn_link',
            field=models.CharField(default='', max_length=80, verbose_name='رابط زر الضغط'),
        ),
    ]
