# Generated by Django 3.2.12 on 2022-03-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_mainicon_btn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainicon',
            name='btn_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page'),
        ),
    ]
