# Generated by Django 3.2.12 on 2022-03-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_mainicon_btn_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='btn_link',
            new_name='btn_url',
        ),
        migrations.RenameField(
            model_name='mainicon',
            old_name='btn_link',
            new_name='btn_url',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='link',
            new_name='page_url',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='link',
            new_name='sub_page_url',
        ),
    ]
