# Generated by Django 3.2.12 on 2022-03-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_menu_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pure_html',
            field=models.TextField(default='<div></div>', verbose_name='كود HTML'),
        ),
    ]
