# Generated by Django 3.2.12 on 2022-03-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_page_pure_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pure_html',
            field=models.TextField(blank=True, default='<div></div>', verbose_name='كود HTML'),
        ),
    ]
