# Generated by Django 3.2.12 on 2022-03-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_carousel_btn_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'قائمة فرعية', 'verbose_name_plural': 'قوائم فرعية'},
        ),
        migrations.AlterField(
            model_name='submenu',
            name='sub_page_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='رابط الصفحة الفرعية'),
        ),
    ]
