# Generated by Django 3.2.12 on 2022-04-07 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220329_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img_src',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='صورة مميزة'),
            preserve_default=False,
        ),
    ]
