# Generated by Django 3.2.12 on 2022-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_page_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_src',
            field=models.CharField(default='home/img/pages/', max_length=80, verbose_name='رابط الصورة'),
        ),
    ]
