# Generated by Django 3.2.12 on 2022-04-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_page_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_src',
            field=models.ImageField(upload_to='img/pages', verbose_name='صورة مميزة'),
        ),
    ]
