# Generated by Django 3.2.12 on 2022-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_page_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img_src',
            field=models.ImageField(upload_to='carousels', verbose_name='صورة الشريحة'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='img_src',
            field=models.ImageField(upload_to='featurettes', verbose_name='صورة الموضوع'),
        ),
    ]
