# Generated by Django 3.2.13 on 2022-06-14 07:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان الموضوع')),
                ('muted_title', models.CharField(max_length=80, verbose_name='كلمة مميزة')),
                ('text', models.TextField(verbose_name='النص الفرعي')),
                ('style', models.CharField(choices=[('R', 'يمين'), ('L', 'يسار')], max_length=1, verbose_name='تنسيق العرض')),
                ('img_src', models.ImageField(upload_to='featurettes', verbose_name='صورة الموضوع')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'موضوع متميز',
                'verbose_name_plural': 'موضوعات متميزة',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=80, verbose_name='الصفحة')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('has_sub', models.BooleanField(default=False, verbose_name='زر قائمة فرعية؟')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'قائمة',
                'verbose_name_plural': 'قوائم',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان الصفحة')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوى الصفحة')),
                ('pure_html', models.TextField(blank=True, verbose_name='كود HTML')),
                ('url', models.SlugField(unique=True, verbose_name='رابط الصفحة')),
                ('img_src', models.ImageField(upload_to='pages', verbose_name='صورة مميزة')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'صفحات',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_page_name', models.CharField(max_length=80, verbose_name='الصفحة الفرعية')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب الفرعي')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menu', verbose_name='تابع لـ')),
                ('sub_page_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='رابط الصفحة الفرعية')),
            ],
            options={
                'verbose_name': 'قائمة فرعية',
                'verbose_name_plural': 'قوائم فرعية',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='page_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='رابط الصفحة'),
        ),
        migrations.CreateModel(
            name='MainIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان الأيقونة')),
                ('text', models.TextField(verbose_name='النص الفرعي')),
                ('icon_class', models.CharField(max_length=80, verbose_name='FontAwesome Class')),
                ('btn_text', models.CharField(default='no-button', max_length=80, verbose_name='زر الضغط')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('btn_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='رابط زر الضغط')),
            ],
            options={
                'verbose_name': 'أيقونة',
                'verbose_name_plural': 'أيقونات',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='الاسم')),
                ('msg_type', models.CharField(choices=[('suggest', 'مقترح'), ('complain', 'شكوى')], max_length=8, verbose_name='نوع الرسالة')),
                ('msg_text', models.TextField(verbose_name='الرسالة')),
                ('msg_created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('msg_modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'نموذج تواصل',
                'verbose_name_plural': 'نماذج التواصل',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='عنوان الشريحة')),
                ('text', models.TextField(verbose_name='النص الفرعي')),
                ('img_src', models.ImageField(upload_to='carousels', verbose_name='صورة الشريحة')),
                ('btn_text', models.CharField(default='no-button', max_length=80, verbose_name='زر الضغط')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('btn_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page', verbose_name='رابط زر الضغط')),
            ],
            options={
                'verbose_name': 'شريحة عرض',
                'verbose_name_plural': 'شرائح العرض',
            },
        ),
    ]
