# Generated by Django 3.2.12 on 2022-03-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
    ]
