# Generated by Django 3.2.12 on 2022-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_team_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(default='Egypt', max_length=200),
            preserve_default=False,
        ),
    ]
