# Generated by Django 3.2.12 on 2022-03-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20220324_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='isDirectorAuth',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='isFinanceAuth',
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinanceAuth', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق الماليات؟')),
                ('isDirectorAuth', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق المدير؟')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='مسلسل الفاتورة')),
            ],
            options={
                'verbose_name': 'تصديق',
                'verbose_name_plural': 'تصديقات',
            },
        ),
    ]
