# Generated by Django 3.2.12 on 2022-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20220326_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='isDirectorAuth',
            field=models.CharField(choices=[('H', 'معلق'), ('A', 'مقبول'), ('R', 'مرفوض')], default='H', max_length=1, verbose_name='تصديق المدير؟'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='isFinanceAuth',
            field=models.CharField(choices=[('H', 'معلق'), ('A', 'مقبول'), ('R', 'مرفوض')], default='H', max_length=1, verbose_name='تصديق الماليات؟'),
        ),
    ]
