# Generated by Django 3.2.12 on 2022-03-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20220326_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeauth',
            options={'verbose_name': 'تصديق الماليات', 'verbose_name_plural': 'تصديقات الماليات'},
        ),
    ]
