# Generated by Django 3.2.12 on 2022-03-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_financeauth_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorauth',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='مسلسل الفاتورة'),
        ),
    ]
