# Generated by Django 3.2.12 on 2022-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_directorauth_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeauth',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='isDirectorAuth',
            field=models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق المدير؟'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='isFinanceAuth',
            field=models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق الماليات؟'),
        ),
        migrations.DeleteModel(
            name='DirectorAuth',
        ),
        migrations.DeleteModel(
            name='FinanceAuth',
        ),
    ]
