# Generated by Django 3.2.13 on 2022-06-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('commercialRegister', models.IntegerField(unique=True, verbose_name='رقم السجل التجاري')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'شركات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'أقسام',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='رقم الفاتورة')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('isFinanceAuth', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق الماليات؟')),
                ('isDirectorAuth', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='H', max_length=1, verbose_name='تصديق المدير؟')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company', verbose_name='اسم الشركة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'فواتير',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('militaryNumber', models.IntegerField(unique=True, verbose_name='الرقم العسكري')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'أفراد',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العنصر')),
                ('quantity', models.SmallIntegerField(verbose_name='الكمية المضافة')),
                ('price', models.FloatField(verbose_name='سعر الوحدة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.department', verbose_name='القسم التابع له')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='مضاف للفاتورة')),
            ],
            options={
                'verbose_name': 'عنصر',
                'verbose_name_plural': 'عناصر',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='entryPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.person', verbose_name='إدخال البيانات'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.person', verbose_name='رئيس القسم'),
        ),
    ]
