# Generated by Django 3.2.13 on 2022-06-17 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='تصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='الكمية المضافة')),
                ('price', models.FloatField(verbose_name='سعر الوحدة')),
            ],
            options={
                'verbose_name': 'عملية شراء',
                'verbose_name_plural': 'عمليات شراء',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'صنف', 'verbose_name_plural': 'أصناف'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='isDirectorAuth',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='isFinanceAuth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_state',
            field=models.CharField(choices=[('A', 'في المشتريات'), ('B', 'في الأمن'), ('C', 'في الماليات'), ('D', 'في الإدارة')], default='A', max_length=1, verbose_name='حالة الفاتورة الحالية'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='قسم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.company', verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='entryPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='إدخال البيانات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='صنف'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.invoice', verbose_name='فاتورة'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ManyToManyField(to='invoice.Item', verbose_name='صنف'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.category', verbose_name='تصنيف الصنف'),
            preserve_default=False,
        ),
    ]
