# Generated by Django 3.2.13 on 2022-06-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20220617_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.category', verbose_name='تصنيف الفاتورة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.category', verbose_name='تصنيف الصنف'),
            preserve_default=False,
        ),
    ]
