# Generated by Django 3.2.13 on 2022-06-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20220617_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchases',
            field=models.ManyToManyField(to='invoice.Purchase', verbose_name='أصناف الفاتورة'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.item', verbose_name='صنف'),
            preserve_default=False,
        ),
    ]
