# Generated by Django 3.2.13 on 2022-06-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20220617_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchases',
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchases',
            field=models.ManyToManyField(to='invoice.Purchase', verbose_name='أصناف الفاتورة'),
        ),
    ]
