# Generated by Django 3.2.13 on 2022-06-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20220617_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.company', verbose_name='موجه للقسم'),
        ),
    ]
