# Generated by Django 3.2.13 on 2022-06-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.department', verbose_name='موجه للقسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.company', verbose_name='اسم الشركة'),
        ),
    ]
