# Generated by Django 3.2.13 on 2022-06-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20220617_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
    ]
