# Generated by Django 3.2.13 on 2022-06-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_remove_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.invoice', verbose_name='فاتورة'),
            preserve_default=False,
        ),
    ]
