# Generated by Django 3.2.13 on 2022-07-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0016_auto_20220730_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.category', verbose_name='تصنيف الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.company', verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='current_state',
            field=models.CharField(blank=True, choices=[('A', 'في المشتريات'), ('B', 'في الأمن'), ('C', 'في الماليات'), ('D', 'في الإدارة')], default='A', max_length=1, null=True, verbose_name='حالة الفاتورة الحالية'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.department', verbose_name='موجه للقسم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='entryPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='إدخال البيانات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.category', verbose_name='تصنيف الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='صنف'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
