# Generated by Django 3.2.13 on 2022-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20220730_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='الكمية'),
        ),
    ]
