# Generated by Django 3.2.13 on 2022-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20220730_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة'),
        ),
    ]
