# Generated by Django 3.2.13 on 2022-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_auto_20220731_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='entryPerson',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='إدخال البيانات'),
        ),
    ]
