# Generated by Django 3.2.13 on 2022-07-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('purchase', 'مكتب المشتريات'), ('finance', 'الماليات'), ('director', 'المدير'), ('security', 'الأمن')], 'verbose_name': 'فاتورة', 'verbose_name_plural': 'فواتير'},
        ),
    ]
