# Generated by Django 3.2.13 on 2022-08-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='commercialRegister',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم السجلل التجاري'),
        ),
    ]
