# Generated by Django 3.2.13 on 2022-08-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_company_commercialregister'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'company')},
        ),
    ]
