# Generated by Django 3.2.13 on 2022-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظة')),
                ('entryPerson', models.CharField(blank=True, max_length=100, null=True, verbose_name='إدخال البيانات')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'ملاحظات',
            },
        ),
    ]
