# Generated by Django 3.2.13 on 2022-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
