# Generated by Django 3.2.13 on 2022-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_state',
            field=models.CharField(blank=True, choices=[(1, 'في المشتريات'), (2, 'في الأمن'), (3, 'في الماليات'), (4, 'في الإدارة')], default=1, max_length=1, null=True, verbose_name='حالة الفاتورة الحالية'),
        ),
    ]
