# Generated by Django 3.2.13 on 2022-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_alter_invoice_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_state',
            field=models.CharField(blank=True, choices=[('A', 'في المشتريات'), ('B', 'في الأمن'), ('C', 'في الماليات'), ('D', 'في الإدارة'), ('F', 'منتهية')], default='A', max_length=1, null=True, verbose_name='حالة الفاتورة الحالية'),
        ),
    ]
