# Generated by Django 3.2.13 on 2022-08-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_alter_invoice_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
