# Generated by Django 3.2.13 on 2022-08-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0037_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='الفاتورة'),
        ),
    ]
