# Generated by Django 3.2.13 on 2022-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_alter_invoice_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_state',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'في المشتريات'), (2, 'في الأمن'), (3, 'في الماليات'), (4, 'في الإدارة'), (5, 'منتهية')], default=1, null=True, verbose_name='حالة الفاتورة الحالية'),
        ),
    ]
