# Generated by Django 3.2.13 on 2022-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0041_alter_comment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='وصف'),
        ),
    ]
