# Generated by Django 3.2.13 on 2022-08-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='-', max_length=200, verbose_name='وصف'),
        ),
    ]
